os_version = "20.04"
src_box_name = "bento/ubuntu-20.04-arm64"
salt_provision_pyenv_deps = "make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev llvm libncurses5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev"
salt_provision_python_version = "3.8.13"
salt_provision_version = "3004.2"
