---
kind: pipeline
name: build-centos-6

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: centos-6
  privileged: true
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-centos-7

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: centos-7
  privileged: true
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-debian-8

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: debian-8
  privileged: true
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-debian-9

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: debian-9
  privileged: true
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-ubuntu-14

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: ubuntu-14
  privileged: true
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-py2-ubuntu-16

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-ubuntu-16
  privileged: true
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-py3-ubuntu-16

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-ubuntu-16
  privileged: true
  when:
    event:
    - pull_request

---
kind: pipeline
name: build-ubuntu-18

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: saltstack/drone-plugin-kitchen
  settings:
    target: ubuntu-18
  privileged: true
  when:
    event:
    - pull_request

---
kind: signature
hmac: 2065d89588e9f4d0c612f88921f09b8260884dda35af76faced19a3197266a88

...
