---
kind: pipeline
name: Arch

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 0 seconds; sleep 0'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-arch
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-arch
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-arch
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-arch
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: CentOS 6

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 20 seconds; sleep 20'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-centos-6
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-centos-6
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: CentOS 7

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 80 seconds; sleep 80'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-centos-7
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-centos-7
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Debian 8

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 120 seconds; sleep 120'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-debian-8
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-debian-8
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Debian 9

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 160 seconds; sleep 160'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-debian-9
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-debian-9
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Fedora 28

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 200 seconds; sleep 200'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-fedora-28
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-fedora-28
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-fedora-28
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-fedora-28
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Fedora 29

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 240 seconds; sleep 240'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-fedora-29
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-fedora-29
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-fedora-29
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-fedora-29
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Opensuse 15.0

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 280 seconds; sleep 280'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-opensuse-15
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Opensuse 42.3

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 320 seconds; sleep 320'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-opensuse-42
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Ubuntu 14.04

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 180 seconds; sleep 180'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-ubuntu-1404
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Ubuntu 16.04

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 400 seconds; sleep 400'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-ubuntu-1604
  privileged: true
  depends_on:
  - throttle-build

---
kind: pipeline
name: Ubuntu 18.04

platform:
  os: linux
  arch: amd64

steps:
- name: throttle-build
  image: alpine
  commands:
  - "sh -c 'echo Sleeping 440 seconds; sleep 440'"

- name: py2-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-minimal-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py3-minimal
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-minimal-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py2-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py2-full-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

- name: py3-full
  image: saltstack/drone-plugin-kitchen
  settings:
    target: py3-full-ubuntu-1804
  privileged: true
  depends_on:
  - throttle-build

---
kind: signature
hmac: f6ed7a438293006ecd156acd2288114ae28b93aa4298141b44fa0af32172647b

...
