---
<% @vagrant = system('which vagrant 2>&1 >/dev/null') %>
driver:
  name: docker
  use_sudo: false
  privileged: true
  username: root
  volume:
    - /var/run/docker.sock:/var/run/docker.sock
  cap_add:
    - sys_admin
  disable_upstart: false
sudo: false
provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_version: latest
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_bootstrap_options: -X stable <%= ENV['TRAVIS_BRANCH'] %>
  log_level: info
  is_file_root: true
  require_chef: false
  salt_copy_filter:
    - .bundle
    - .git
    - .gitignore
    - .kitchen
    - .kitchen.yml
    - Gemfile
    - Gemfile.lock
    - README.rst
    - .travis.yml
  state_top:
    base:
      "*":
        - git.salt
platforms:
  - name: fedora
    driver_config:
      image: fedora:latest
      run_command: /usr/lib/systemd/systemd
    provisioner:
      salt_bootstrap_options: -X git <%= ENV['TRAVIS_BRANCH'] %> >/dev/null
  - name: centos-7
    driver_config:
      run_command: /usr/lib/systemd/systemd
  - name: centos-6
    driver_config:
      run_command: /sbin/init
      provision_command:
        - yum install -y upstart
    provisioner:
      salt_bootstrap_options: -P -y -x python2.7 -X git <%= ENV['TRAVIS_BRANCH'] %> >/dev/null
  - name: ubuntu-rolling
    driver_config:
      image: ubuntu:rolling
      run_command: /lib/systemd/systemd
    provisioner:
      salt_bootstrap_options: -PX git <%= ENV['TRAVIS_BRANCH'] %> >/dev/null
  - name: ubuntu-16.04
    driver_config:
      run_command: /lib/systemd/systemd
  - name: ubuntu-14.04
    driver_config:
      run_command: /sbin/init
      provision_command:
        - rm -f /sbin/initctl
        - dpkg-divert --local --rename --remove /sbin/initctl
  - name: debian-8
    driver_config:
      run_command: /lib/systemd/systemd
      provision_command:
        - apt-get install -y dbus
  - name: debian-9
    driver_config:
      run_command: /lib/systemd/systemd
  - name: arch
    driver_config:
      image: base/archlinux
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - pacman -Syu --noconfirm systemd
        - systemctl enable sshd
    provisioner:
      salt_bootstrap_options: -X git <%= ENV['TRAVIS_BRANCH'] %> >/dev/null
  - name: opensuse
    driver_config:
      run_command: /usr/lib/systemd/systemd
      provision_command:
        - systemctl enable sshd.service
    provisioner:
      salt_bootstrap_options: -X git <%= ENV['TRAVIS_BRANCH'] %> >/dev/null
<% if @vagrant != false %>
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
      communicator: winrm
      name: vagrant
      gui: true
      username: administrator
      password: Pass@word1
    provisioner:
      init_environment: |
        Clear-Host
        $AddedLocation ="c:\salt"
        $Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"
        $OldPath = (Get-ItemProperty -Path "$Reg" -Name PATH).Path
        $NewPath= $OldPath + ’;’ + $AddedLocation
        Set-ItemProperty -Path "$Reg" -Name PATH –Value $NewPath
      salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1
      salt_bootstrap_options: ''
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
      communicator: winrm
      name: vagrant
      username: Vagrant
      password: vagrant
      gui: true
    provisioner:
      init_environment: |
        Clear-Host
        $AddedLocation ="c:\salt"
        $Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"
        $OldPath = (Get-ItemProperty -Path "$Reg" -Name PATH).Path
        $NewPath= $OldPath + ’;’ + $AddedLocation
        Set-ItemProperty -Path "$Reg" -Name PATH –Value $NewPath
      salt_bootstrap_url: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.ps1
      salt_bootstrap_options: ''
<% end %>
suites:
  - name: py2
    provisioner:
      pillars:
        top.sls:
          base:
            "*":
              - jenkins
        jenkins.sls:
          test_git_url: git://github.com/saltstack/salt.git
          test_git_commit: <%= (ENV['TRAVIS_BRANCH'] == 'master' ? 'develop' : ENV['TRAVIS_BRANCH']) %>
  - name: py3
    excludes:
      - centos-6
    provisioner:
      pillars:
        top.sls:
          base:
            "*":
              - jenkins
        jenkins.sls:
          test_git_url: git://github.com/saltstack/salt.git
          test_git_commit: <%= (ENV['TRAVIS_BRANCH'] == 'master' ? 'develop' : ENV['TRAVIS_BRANCH']) %>
          py3: true
