name: Build Golden Image

on:
  workflow_call:
    inputs:
      distro-name:
        required: true
        type: string
        description: The OS distribution to build
      changed-files:
        required: true
        type: string
        description: JSON string containing information about changed files


env:
  COLUMNS: 160

jobs:
  generate-matrix:
    name: Generate The Build Matrix
    runs-on: ubuntu-latest
    outputs:
      arches: ${{ steps.generate-arches.outputs.arches }}
      versions: ${{ steps.generate-versions.outputs.versions }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Install Python Tools Scripts
        env:
          PIP_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
          PIP_EXTRA_INDEX_URL: https://pypi.org/simple
        run: |
          python3 -m pip install -r requirements/tools.txt

      - name: Generate Versions List
        id: generate-versions
        run: |
          VERSIONS=$(tools images matrix --versions ${{ inputs.distro-name }})
          echo $VERSIONS
          echo "versions=$VERSIONS" >> $GITHUB_OUTPUT

      - name: Generate Arches List
        id: generate-arches
        run: |
          ARCHES=$(tools images matrix --arches ${{ inputs.distro-name }})
          echo $ARCHES
          echo "arches=$ARCHES" >> $GITHUB_OUTPUT

  build:
    name: Build Image
    runs-on:
      - self-hosted
      - image-builder
    needs:
      - generate-matrix
    timeout-minutes: 60  # 1 Hour
    strategy:
      fail-fast: false
      matrix:
        distro-arch: ${{ fromJSON(needs.generate-matrix.outputs.arches) }}
        distro-version: ${{ fromJSON(needs.generate-matrix.outputs.versions) }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp-contrib/setup-packer@v1
        with:
          packer-version: 1.8.4

      - name: Install Python Tools Scripts
        env:
          PIP_INDEX_URL: https://pypi-proxy.saltstack.net/root/local/+simple/
          PIP_EXTRA_INDEX_URL: https://pypi.org/simple
        run: |
          python3 -m pip install -r requirements/tools.txt

      - name: Build Image
        run: |
          tools --timestamps images build-ami --region=${{ inputs.aws-region }} --arch=${{ matrix.distro-arch }} ${{ inputs.distro-name }} ${{ matrix.distro-version }}

      - name: Set Exit Status
        if: always()
        run: |
          mkdir exitstatus
          echo "${{ job.status }}" > exitstatus/${{ github.job }}-${{ inputs.distro-name }}-${{ matrix.distro-version }}-${{ matrix.distro-arch }}

      - name: Upload Exit Status
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: exitstatus
          path: exitstatus
          if-no-files-found: error
