name: CentOS Stream

on:
  - push
  - pull_request

concurrency:
  # If changes are pushed to a PR, stop all running workflows before starting new ones
  group: ${{ github.head_ref || (github.repository == 'saltstack/salt-jenkins' && github.run_id || github.ref_name) }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Build:
    runs-on: macos-12

    timeout-minutes: 30

    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os-arch:
          - amd64
        os-version:
          - 8
          - 9

    steps:

    - name: Install System Dependencies
      run: |
        if [ "x$(which sha256sum)" == "x" ]
        then
          brew install coreutils
        fi
        if [ "x$(which sha256sum)" == "x" ]
        then
          export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
        fi
        if [ "x$(which gsed)" == "x" ]
        then
          brew install gnu-sed
        fi


    - name: Install VirtualBox
      run: |
        #curl https://download.virtualbox.org/virtualbox/6.1.30/VirtualBox-6.1.30-148432-OSX.dmg --output vb.dmg
        #sudo hdiutil attach vb.dmg
        #sudo installer -package /Volumes/VirtualBox/VirtualBox.pkg -target /
        #sudo hdiutil detach /Volumes/VirtualBox
        #brew reinstall --cask virtualbox
        export VIRTUALBOX_VERSION=$(VBoxManage --version)
        echo "VIRTUALBOX_VERSION=${VIRTUALBOX_VERSION}" >> $GITHUB_ENV

    - name: Install Vagrant
      run: |
        brew install --cask vagrant

    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Set Python Cache Key
      run: echo "PY=$(python --version --version | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

    - name: Setup Python Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: python|${{ runner.os }}|${{ env.PY }}

    - name: Install Python Requirements
      run: |
        python -m pip install -r os-images/requirements/py3.6/base.txt

    - name: Show Vagrant Information
      run: |
        vagrant --version
        vagrant plugin list
        echo "VAGRANT_VERSION=$(vagrant --version | cut -d' ' -f2)"  >> $GITHUB_ENV

    - name: Cache Vagrant boxes and plugins
      uses: actions/cache@v3
      with:
        path: |
          ~/.vagrant.d/boxes
          ~/.vagrant.d/gems/${{ env.VAGRANT_VERSION }}/gems/
        key: vagrant|${{ runner.os }}|${{ env.VAGRANT_VERSION }}|${{ env.VIRTUALBOX_VERSION }}|centos-stream|${{ matrix.os-version }}|${{ matrix.os-arch }}

    - name: Vagrant Boxes List
      run: |
        vagrant global-status
        vagrant box list
        # vagrant box update

    - name: Setup Packer
      uses: hashicorp-contrib/setup-packer@v1
      with:
        packer-version: 1.8.2

    - name: Show Packer Information
      run: |
        packer --version
        echo "PACKER_VERSION=$(packer --version)"  >> $GITHUB_ENV

    - name: Cache Packer Plugins
      uses: actions/cache@v3
      with:
        path: |
          ~/.packer/.config/packer/plugins
        key: packer|${{ runner.os }}|${{ env.PACKER_VERSION }}

    - name: Init Packer
      env:
        PACKER_GITHUB_API_TOKEN: "${{ secrets.PACKER_INIT_GH_TOKEN }}"
      run: |
        inv -e build-vagrant --distro=centos-stream --distro-version=${{ matrix.os-version }} --distro-arch=${{ matrix.os-arch }} --init

    - name: Validate Packer Configs
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
      run: |
        inv -e build-vagrant --distro=centos-stream --distro-version=${{ matrix.os-version }} --distro-arch=${{ matrix.os-arch }} --validate

    - name: Pull Image
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
      uses: Wandalen/wretry.action@v1.0.11
      with:
        attempt_limit: 3
        attempt_delay: 90000
        command: |
          inv -e build-vagrant --distro=centos-stream --distro-version=${{ matrix.os-version }} --distro-arch=${{ matrix.os-arch }} --pull

    - name: Build Packer Staging Image
      if: github.event_name == 'pull_request'
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
      run: |
        inv -e build-vagrant --distro=centos-stream --distro-version=${{ matrix.os-version }} --distro-arch=${{ matrix.os-arch }} --force --staging

    - name: Build Packer Image
      if: github.event_name != 'pull_request'
      env:
        VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}
        PACKER_LOG: "1"
        PACKER_DEBUG: "1"
      run: |
        inv -e build-vagrant --distro=centos-stream --distro-version=${{ matrix.os-version }} --distro-arch=${{ matrix.os-arch }} --force
